sequenceDiagram
    Browser->>+SystemServer: GET Request for HTML
    SystemServer-->>+Browser: Response (HTML Content)

    Browser->>+SystemServer: GET Request for CSS
    SystemServer-->>+Browser: Response (CSS Content)

    Browser->>+SystemServer: GET Request for JavaScript
    SystemServer-->>+Browser: Response (JavaScript Content)

    Browser->>+SystemServer: GET Request for JSON Data
    SystemServer-->>+Browser: Response (JSON Data Content)
    
